"""
FastAPI Main Application

This module defines the REST API endpoints for the semantic cache system.

Endpoints:
- POST /query: Submit a natural language query
- GET /cache/stats: Get cache performance statistics
- DELETE /cache: Clear the cache
- GET /health: Health check endpoint

Responsibilities:
- Define API routes and handlers
- Request validation using Pydantic schemas
- Response formatting
- Error handling
- API documentation (auto-generated by FastAPI)
"""

from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from contextlib import asynccontextmanager
import logging

from api.schemas import QueryRequest, QueryResponse, CacheStatsResponse, MessageResponse, HealthResponse
from src.query_engine import QueryEngine
from src.embedding_model import EmbeddingModel
from src.clustering import FuzzyClusterer
from src.semantic_cache import SemanticCache
from src.text_cleaner import TextCleaner
from src.paths import CLUSTERS_PATH, EMBEDDINGS_PATH
import config

# Setup logging
logging.basicConfig(
    level=getattr(logging, config.LOG_LEVEL),
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Global instances
query_engine = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Initialize all components on application startup.
    """
    global query_engine
    
    logger.info("="*70)
    logger.info("SEMANTIC CACHE API - STARTING")
    logger.info("="*70)
    
    # Validate required files exist
    logger.info("Validating required model files...")
    if not EMBEDDINGS_PATH.exists():
        logger.error(f"Embeddings file not found: {EMBEDDINGS_PATH}")
        raise FileNotFoundError(
            f"Required file missing: {EMBEDDINGS_PATH}\n"
            f"Run: python generate_embeddings.py"
        )
    
    if not CLUSTERS_PATH.exists():
        logger.error(f"Clusters file not found: {CLUSTERS_PATH}")
        raise FileNotFoundError(
            f"Required file missing: {CLUSTERS_PATH}\n"
            f"Run: python train_clustering.py"
        )
    
    # Initialize components
    logger.info("Loading embedding model...")
    embedding_model = EmbeddingModel(config.EMBEDDING_MODEL_NAME, config.EMBEDDING_DEVICE)
    embedding_model.load_model()
    
    logger.info("Loading clustering model...")
    clusterer = FuzzyClusterer(n_clusters=config.N_CLUSTERS)
    clusterer.load(str(CLUSTERS_PATH))
    
    logger.info("Initializing semantic cache...")
    cache = SemanticCache(
        similarity_threshold=config.CACHE_SIMILARITY_THRESHOLD,
        use_clustering=config.USE_CLUSTERING
    )
    
    logger.info("Initializing text cleaner...")
    text_cleaner = TextCleaner()
    
    logger.info("Initializing query engine...")
    query_engine = QueryEngine(
        embedding_model=embedding_model,
        clusterer=clusterer,
        semantic_cache=cache,
        text_cleaner=text_cleaner
    )
    
    logger.info("="*70)
    logger.info("API READY - Server started successfully")
    logger.info("="*70)
    
    yield
    
    logger.info("Shutting down...")


# Initialize FastAPI app
app = FastAPI(
    title="Semantic Cache API",
    description="Natural language query system with semantic caching",
    version="1.0.0",
    lifespan=lifespan
)

# Configure CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/", tags=["Root"])
async def root():
    """Root endpoint with API information."""
    return {
        "message": "Semantic Cache API",
        "version": "1.0.0",
        "endpoints": {
            "POST /query": "Submit a natural language query",
            "GET /cache/stats": "Get cache statistics",
            "DELETE /cache": "Clear cache",
            "GET /health": "Health check"
        }
    }


@app.get("/health", response_model=HealthResponse, tags=["Health"])
async def health_check():
    """Health check endpoint."""
    return {
        "status": "healthy",
        "version": "1.0.0",
        "components": {
            "query_engine": "operational" if query_engine else "not initialized",
            "semantic_cache": "operational",
            "embedding_model": "operational",
            "clustering": "operational"
        }
    }


@app.post("/query", response_model=QueryResponse, tags=["Query"])
async def query(request: QueryRequest):
    """
    Process a natural language query.
    """
    if query_engine is None:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Query engine not initialized"
        )
    
    # Validate input
    if not request.query or len(request.query.strip()) == 0:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Query text cannot be empty"
        )
    
    try:
        # Process query
        result = query_engine.process_query(
            query_text=request.query,
            use_cache=request.use_cache,
            top_k=request.top_k
        )
        
        # Format response
        return QueryResponse(
            query=result['query'],
            cache_hit=result['cache_hit'],
            matched_query=result['matched_query'],
            similarity_score=result['similarity_score'],
            result=result['result'],
            dominant_cluster=result['dominant_cluster'],
            processing_time_ms=result['processing_time_ms']
        )
    
    except Exception as e:
        logger.error(f"Error processing query: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error processing query: {str(e)}"
        )


@app.get("/cache/stats", response_model=CacheStatsResponse, tags=["Cache"])
async def get_cache_stats():
    """
    Get semantic cache performance statistics.
    
    Returns:
        Cache statistics including hit rate, size, etc.
    """
    if query_engine is None:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Query engine not initialized"
        )
    
    try:
        stats = query_engine.get_cache_stats()
        
        return CacheStatsResponse(
            total_entries=stats['total_entries'],
            total_queries=stats['total_queries'],
            hit_count=stats['hit_count'],
            miss_count=stats['miss_count'],
            hit_rate=stats['hit_rate'],
            miss_rate=stats['miss_rate'],
            similarity_threshold=stats['similarity_threshold'],
            use_clustering=stats['use_clustering']
        )
    
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error getting cache stats: {str(e)}"
        )


@app.delete("/cache", response_model=MessageResponse, tags=["Cache"])
async def clear_cache():
    """Clear all entries from the semantic cache."""
    if query_engine is None:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Query engine not initialized"
        )
    
    try:
        query_engine.semantic_cache.clear()
        
        return MessageResponse(
            message="Cache cleared successfully",
            success=True
        )
    
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error clearing cache: {str(e)}"
        )
